"""PostgreSQL pgvector implementation of vector search."""

from __future__ import annotations

import asyncio
import json
import math
from collections.abc import Mapping, Sequence
from dataclasses import asdict

from ...interfaces.client import EmbeddingClient
from ...interfaces.stores import VectorSearchStore
from ...models.document import ScoredTextChunk, TextChunk
from .postgres_bm25_search_store import PostgresBM25SearchStore


class PostgresVectorSearchStore(PostgresBM25SearchStore, VectorSearchStore):
    """Search a configured ``embedding`` column using pgvector cosine distance."""

    def __init__(
        self,
        dsn: str,
        client: EmbeddingClient,
        *,
        table_name: str = "rag_text_chunks",
    ):
        super().__init__(dsn, table_name=table_name)
        self._embedding_client = client
        self._table_name = table_name

    async def _a_embedding(self, query_text: str) -> list[float]:
        """Generate and validate the asynchronous query embedding."""
        return self._validate_embedding(await self._embedding_client.a_embedding(query_text))

    def _upsert_chunks(self, cursor: object, chunks: Sequence[TextChunk]) -> None:
        """Upsert chunks together with embeddings generated by the configured client."""
        query = self._query(
            """
                INSERT INTO {table} (
                    id, document_id, content, chunk_index, source, start_offset,
                    end_offset, metadata, embedding
                ) VALUES (%s, %s, %s, %s, %s::jsonb, %s, %s, %s::jsonb, %s::vector)
                ON CONFLICT (id) DO UPDATE SET
                    document_id = EXCLUDED.document_id,
                    content = EXCLUDED.content,
                    chunk_index = EXCLUDED.chunk_index,
                    source = EXCLUDED.source,
                    start_offset = EXCLUDED.start_offset,
                    end_offset = EXCLUDED.end_offset,
                    metadata = EXCLUDED.metadata,
                    embedding = EXCLUDED.embedding
            """
        )
        values = [
            (
                chunk.id,
                chunk.document_id,
                chunk.content,
                chunk.index,
                json.dumps(asdict(chunk.source)),
                chunk.start_offset,
                chunk.end_offset,
                json.dumps(chunk.metadata),
                self._vector_literal(
                    self._validate_embedding(self._embedding_client.embedding(chunk.content))
                ),
            )
            for chunk in chunks
        ]
        cursor.executemany(query, values)  # type: ignore[attr-defined]

    def search(
        self,
        query_text: str,
        *,
        top_k: int,
        filters: Mapping[str, object],
    ) -> list[ScoredTextChunk]:
        """Generate a query embedding and synchronously search pgvector."""
        if not query_text.strip():
            return []
        embedding = self._validate_embedding(self._embedding_client.embedding(query_text))
        return self._search_embedding(embedding, top_k=top_k, filters=filters)

    async def asearch(
        self,
        query_text: str,
        *,
        top_k: int,
        filters: Mapping[str, object],
    ) -> list[ScoredTextChunk]:
        """Generate a query embedding and search pgvector without blocking the loop."""
        if not query_text.strip():
            return []
        embedding = await self._a_embedding(query_text)
        return await asyncio.to_thread(
            self._search_embedding, embedding, top_k=top_k, filters=filters
        )

    def _search_embedding(
        self,
        embedding: list[float],
        *,
        top_k: int,
        filters: Mapping[str, object],
    ) -> list[ScoredTextChunk]:
        query = self._query(
            "SELECT id, document_id, content, chunk_index, source, start_offset, "
            "end_offset, metadata, 1 - (embedding <=> %s::vector) AS score "
            "FROM {table} WHERE embedding IS NOT NULL"
        )
        parameters: list[object] = [self._vector_literal(embedding)]
        if filters:
            query += self._query(" AND metadata @> %s::jsonb")
            parameters.append(json.dumps(dict(filters)))
        query += self._query(" ORDER BY embedding <=> %s::vector, id ASC LIMIT %s")
        parameters.extend((self._vector_literal(embedding), top_k))

        with self._connect() as connection, connection.cursor() as cursor:
            cursor.execute(query, parameters)
            return [
                ScoredTextChunk(
                    chunk=self._to_chunk(row[:8]),
                    score=self._required_float(row[8], field="score"),
                )
                for row in cursor.fetchall()
            ]

    @staticmethod
    def _validate_embedding(values: list[float]) -> list[float]:
        if not values or any(
            not isinstance(value, (int, float))
            or isinstance(value, bool)
            or not math.isfinite(value)
            for value in values
        ):
            raise ValueError("embedding must contain at least one finite number")
        return [float(value) for value in values]

    @staticmethod
    def _vector_literal(values: list[float]) -> str:
        """Format values for PostgreSQL's ``vector`` input syntax."""
        return "[" + ",".join(str(value) for value in values) + "]"
